version: '3.8'

services:
  backend:
    build: .
    working_dir: /rails/service
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: service
      MYSQL_PASSWORD: service_password
      SERVICE_DATABASE_PASSWORD: service_password
    volumes:
      # - type: bind
      #   source: ./service
      #   target: /service
      - .:/rails
    # command: bash -c "bundle exec rails server -b 0.0.0.0 -p 3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - db

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: service_production
      MYSQL_USER: service
      SERVICE_DATABASE_PASSWORD: service_password
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
